### ISSUE TITLE
Does ilp3 invalidate the existing ilp architecture? 

### ISSUE THREAD

**Issue by nathanawmk** [emschwartz/ilp3#21]
Hi!

ilp3 looks very promising and hopeful. Does ilp3 invalidate the existing ilp architecture? 

Regards,

Nathan Aw Ming Kun

**Comment by emschwartz** [comment]
Hi Nathan,

We've ended up porting a lot of the lessons from this experiment over to the normal ILP stack.

- We introduced packets with no destination amounts in https://github.com/interledger/rfcs/pull/323
- We put most of the fields from the "Ledger Transfer" object into the ILP packet in https://github.com/interledger/rfcs/pull/361 (based on the discussion in https://github.com/interledger/rfcs/issues/359)
- We added data to the ILP Fulfillment Response packet (necessary for end-to-end quoting) in https://github.com/interledger/rfcs/pull/337
- We're bringing chunked payments and end-to-end quoting to the normal stack in https://github.com/interledger/rfcs/pull/351 and [emschwartz/ilp-psk2](https://github.com/emschwartz/ilp-psk2)

At this point I think the main substantive difference between "ilp3" and what the main Interledger stack is going with now (loosely called ILPv4) is that we decided it is worth having a specific encoding for the packet. To me the main arguments for the packet encoding (as opposed to having an abstractly defined packet) were a) having a packet makes it easier to later extend the protocol with additional fields that intermediaries will pass on even if they don't understand them and b) it removes the overhead of re-encoding the packet at every step. @justmoon wrote up an explanation of why we chose OER in https://github.com/interledger/rfcs/pull/362

**Comment by nathanawmk** [comment]
Hi @emschwartz ,

Thanks -- Understood. Great stuff.

Question: With all these rapid updates, what are some of the most pressing issues that one can find to help and when will interledger be production ready? 

Nathan Aw

**Comment by emschwartz** [comment]
A lot of that has actually been implemented already and is just waiting on some review comments (https://github.com/interledgerjs/ilp-connector/pull/401, https://github.com/interledgerjs/ilp/pull/122). If you're looking for ways to contribute now, it might be easiest to look through the Interledger RFCs and post issues if anything is unclear (always very useful to have fresh eyes look at those sorts of things). Comments are also very welcome on https://github.com/interledger/rfcs/pull/351 and https://github.com/interledger/rfcs/pull/364.

We're hoping to get a small live network going (over XRP to start and then adding the other integrations in) in the next couple of weeks. There are definitely going to be bugs in the software still but we're feeling pretty good about settling on the ILPv4 protocol. If you'd be interested in participating in that, we can peer our connectors once we start that up!

**Comment by nathanawmk** [comment]
For sure, been following all the RFCs and will ask clarification questions! 

I am definitely, definitely keen on participating in the ILPv4 protocol. I can also help out with testing, documentation and with the build of custom plugins for ledgers etc.

Is there rocket chat for the interledger community? Or any monthly calls.  

Nathan Aw

**Comment by emschwartz** [comment]
Sounds great! We have a Gitter chat and have bi-weekly calls that you should definitely join: https://interledger.org/community.html

**Comment by nathanawmk** [comment]
Sure! am happy to be part of this cool ground breaking project. Have just joined the gitter chat and share some comments to introduce myself. meantime, will dive into the RFCs!
