### ISSUE TITLE
Option for HTTP proxy

### ISSUE THREAD

**Issue by dappelt** [emschwartz/ilp3#5]
I added some code for using an HTTP proxy, thought you might want to include something similar. Makes it easier to see (and mess) with the HTTP requests sent on the wire.

In http.js
```js
const HttpsProxyAgent = require('https-proxy-agent')
...
      response = await fetch(url.format(parsedUri, { auth: false }), {
        method: 'POST',
        headers,
        body: transfer.data,
        compress: false,
        agent: new HttpsProxyAgent('http://127.0.0.1:8080')
      })
```

**Comment by emschwartz** [comment]
Couldn't you just set the `uri` to point to your proxy instead?

**Comment by dappelt** [comment]
No, `uri` needs to point at the connector. An [HTTP proxy](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers) just forwards requests/responses.

To give a bit more background, the reason I bring this up is that there are security testing tools that act as an HTTP proxy (e.g. Burp Suite). Routing all HTTP traffic through such a tool makes it easy to analyze and manipulate HTTP requests/responses.
