### ISSUE TITLE
Race Condition when adjusting balances

### ISSUE THREAD

**Issue by dappelt** [emschwartz/ilp3#7]
balance.js [caches](https://github.com/emschwartz/ilp3/blob/master/lib/middleware/balance.js#L21-L23) account balances. This could result in a race condition. For example:

For two requests arriving at the same time and with the same`transfer.from`, the check if an account is cached (line 21) evaluates to false for both. Whichever db read returns first will initialize the cached balance and move on to adjust the balance (line 58). However, when the second db read returns it overwrites the adjusted balance of the first request.

Solution: Make sure that the check if an account exists and the DB read is atomic.

Also, make sure there is no race condition when you write back the balance to the DB (line 83).

**Comment by emschwartz** [comment]
Oops, closed the wrong issue with that commit

**Comment by emschwartz** [comment]
I fixed the first part of the issue but I'm not sure what you meant by "make sure there is no race condition when you write back the balance to the DB (line 83)." Do you see a race condition there now?

**Comment by dappelt** [comment]
I thought there is a race condition in the rollback logic, but at a second glance, it looks safe.
